# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  profiles:
    active: dev
  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    robert: DEBUG
    org.springframework: WARN