server:
  port: 9999
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
spring:
  main.allow-bean-definition-overriding: true
  profiles.active: dev,h2
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: CustomHikariPool
      auto-commit: false
management.endpoints.web.exposure.include: logfile,auditevents,httptrace,beans,metrics,info
robert:
  registrationEnabled: true
  defaultMailReceiver: test@123.pl