server:
  undertow:
    worker-threads: 4

spring:
  profiles:
    active: dev
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    dbcp2:
      max-total: 4


logging:
  level:
    robert: DEBUG
    org.hibernate: WARN

robert:
  registrationEnabled: true