server.undertow:
  io-threads: 1
  worker-threads: 4
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/debts?verifyServerCertificate=false&useSSL=false&requireSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: debtsUser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 4
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: validate
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
robert:
  registrationEnabled: false
  defaultMailReceiver: invoice.writer@gmail.com