server.undertow:
  io-threads: 1
  worker-threads: 4
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/debts?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: debtsUser
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 4
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: validate
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
logging:
  level:
    robert: info
    io.undertow: off
    org.hibernate: error
    org.springframework: error
    org.springframework.boot.context.embedded: info
robert.registrationEnabled: false