spring:
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1
  h2.console:
    enabled: true
    path: /console
    settings.web-allow-others: true
  jpa:
    properties:
      hibernate:
        show_sql: true
robert.registrationEnabled: true