spring:
  datasource:
    url: jdbc:mysql://localhost:3306/debts?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    show-sql: true