logging:
  level:
    robert: debug
    org.hibernate: error
    org.springframework: error
    org.springframework.boot.context.embedded: info

spring:
  profiles:
    active: dev
  datasource:
    dbcp2:
      max-total: 4

server:
  undertow:
    worker-threads: 4
    io-threads: 4

robert:
  registrationEnabled: true