spring:
  datasource:
    hikari:
      maximum-pool-size: 1
  h2.console:
    enabled: true
    path: /console
    settings.web-allow-others: true
  jpa:
    properties:
      hibernate:
      #show_sql: true