logging:
  level:
    robert: debug
    org.hibernate: error
    org.springframework: error
    org.springframework.boot.context.embedded: info
  file: app.log
#
spring:
  profiles.active: dev
  jackson.serialization.indent_output: true
  datasource.dbcp2.max-total: 4
#
server.undertow:
  io-threads: 1
  worker-threads: 4
#
management.contextPath: /actuator
#
robert.registrationEnabled: true