server:
  undertow:
    worker-threads: 4

spring:
  profiles:
    active: dev
  datasource:
    dbcp2:
      max-total: 4

logging:
  level:
    robert: debug
    org.hibernate: warn
    org.springframework: error
    org.springframework.boot.context.embedded: info

robert:
  registrationEnabled: true