server.port: 9999
spring:
  profiles.active: dev,oauth2
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: CustomHikariPool
      auto-commit: false
logging:
  level:
    robert: debug
    org.hibernate: warn
    org.springframework: warn
    org.springframework.boot.context.embedded: info
  file: app.log
management.endpoints.web.exposure.include: logfile,auditevents,httptrace,beans,metrics,info
robert.registrationEnabled: true